[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # Switch context based on the cursor position
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # Judge filetype based on the cursor position
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Color scheme
repo = 'vim-scripts/Wombat'
hook_add = '''
  set t_Co=256
  " colorscheme should be set after source. So, it is executed at VimEnter.
  " This might provent us from event occuring. Nested solves this situation.
  au MyAutoCmd VimEnter * nested colorscheme wombat
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'Shougo/denite.nvim'

depends = ['neomru.vim']
on_event = 'BufRead'
hook_add = '''

nnoremap [denite] <Nop>
nmap <space> [denite]
nmap <silent> [denite]t :<C-u>Denite filetype<CR>
"nmap <silent> [denite] :<C-u>Denite file_rec<CR>
nmap <silent> [denite]l :<C-u>Denite line<CR>
nmap <silent> [denite]g :<C-u>Denite grep<CR>
nmap <silent> [denite]<C-g> :<C-u>DeniteCursorWord grep<CR>
nmap <silent> [denite]m :<C-u>Denite file_mru<CR>
nmap <silent> [denite]y :<C-u>Denite neoyank<CR>
nmap <silent> [denite]r :<C-u>Denite -resume<CR>
"nmap <silent> [denite] :<C-u>Denite -resume -immediately -select=+1<CR>
"nmap <silent> [denite] :<C-u>Denite -resume -immediately -select=-1<CR>
"nmap <silent> [denite] :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/dotfiles']}])<CR>
nnoremap ml :<C-u>call denite#start([{'name': 'file_rec', 'args': [g:memolist_path]}])<CR>
'''
hook_post_source = '''
call denite#custom#var('file_rec', 'command',
\ ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
call denite#custom#var('grep', 'command',
\ ['pt', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
call denite#custom#var('grep', 'default_opts', [])
call denite#custom#var('grep', 'recursive_opts', [])
'''

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
au BufRead,BufNewFIle *.md set filetype=markdown
'''
[[plugins]]
repo = 'Shougo/junkfile.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

#[[plugins]]
#repo = 'vim-scripts/confirm-quit'


[[plugins]]
repo = 'rhysd/vim-grammarous'

#[[plugins]]
#repo = 'jreybert/vimagit'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'ujihisa/repl.vim'

[[plugins]]
repo = 'basyura/TweetVim'
