- hosts: localhost
  user: root
  tasks:
  # Packages
   - package: name=git state=latest
   - package: name=fonts-ricty-diminished state=latest     
   - package: name=tmux state=latest
   - package: name=tmuxinator state=latest
   - package: name=rxvt-unicode-256color state=latest
   - package: name=xmonad state=latest
   - package: name=xmobar state=latest
   - package: name=dmenu state=latest
   ## Zsh
   - package: name=zsh state=latest
   - shell: chsh -s /usr/bin/zsh tomo
   ## Golang
   - package: name=golang state=latest
 #  - name: peco
 #    shell: go get github.com/peco/peco/cmd/peco 
   ## Python
   - package: name=python-dev state=latest
   - package: name=python-pip state=latest
   - package: name=python3-dev state=latest
   - package: name=python3-setuptools state=latest
   - shell: easy_install3 pip
   ## NVIM
   - package: name=software-properties-common state=latest
   - apt_repository: repo='ppa:neovim-ppa/unstable' state=present
   - apt: update_cache=yes
   - package: name=neovim state=latest
   - name: vi-alternative#
     shell: update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
   - name: vi-alternative
     shell: | 
             update-alternatives --config vi <<EOF | grep nvim | tail -1 | awk '{print $1}' | update-alternatives --config vi
             EOF
   - name: vim-alternative#
     shell: update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
   - name: vim-alternative
     shell: |
             update-alternatives --config vim <<EOF | grep nvim | tail -1 | awk '{print $1}' | update-alternatives --config vim
             EOF
   - name: editor-alternative#
     shell: update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
   - name: vi-alternative
     shell: |
             update-alternatives --config editor <<EOF | grep nvim | tail -1 | awk '{print $1}' | update-alternatives --config editor
             EOF
   ## UIM-SKK
   - package: name=uim state=latest
   - package: name=uim-skk state=latest
